### ISSUE TITLE
Building Android fails on rn-qr-generator:verifyReleaseResources task

### ISSUE THREAD

**Issue by fnando** [gevgasparyan/rn-qr-generator#1]
Hi there!

Thanks for doing this project. It's notably faster to render QRCode with it than with other SVG-based solutions I've tried.

I'm trying to add this module to my project and everything worked fine when running iOS' simulator. But when I tried running this on both an emulator and a real device, and the build failed with the message below.

Any tips on how to fix it, or how to debug the issue?

```
> Task :rn-qr-generator:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rn-qr-generator:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2740: error: resource android:attr/fontStyle not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2741: error: resource android:attr/font not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2742: error: resource android:attr/fontWeight not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2743: error: resource android:attr/fontVariationSettings not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2744: error: resource android:attr/ttcIndex not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2908: error: resource android:attr/startX not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2911: error: resource android:attr/startY not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2914: error: resource android:attr/endX not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2917: error: resource android:attr/endY not found.
  myapp/node_modules/rn-qr-generator/android/build/intermediates/res/merged/release/values/values.xml:2925: error: resource android:attr/offset not found.
  error: failed linking references.
  


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8m 27s
1311 actionable tasks: 1180 executed, 131 up-to-date
error Failed to build the app. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew build -x lint
    at makeError (myapp/node_modules/execa/index.js:174:9)
    at Function.module.exports.sync (myapp/node_modules/execa/index.js:338:15)
    at buildApk (myapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:190:22)
    at runOnSpecificDevice (myapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:171:7)
    at buildAndRun (myapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:156:12)
    at then.result (myapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gevorg94** [comment]
Hey @fnando 
what is the version of your react-native?

**Comment by fnando** [comment]
Ouch, sorry for opening the ticket without giving more info about my environment. 🤦‍♂️ 

There you go:

```
$ react-native info                          
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 64.34 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.asdf/installs/nodejs/10.16.3/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.asdf/installs/nodejs/10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28
      Build Tools: 28.0.3, 29.0.0
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.10.2 => 16.10.2 
    react-native: 0.61.5 => 0.61.5
```

I'm also using `rn-qr-generator@v1.0.1`.

**Comment by gevorg94** [comment]
@fnando I've checked it with the following version on android
```
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "rn-qr-generator": "^1.0.1"
  },
```
And my build.gradle is

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

```
And it works fine.

Can you please try to remove node modules and install it again?

**Comment by gevgasparyan** [comment]
Hey @fnando, were you able to fix the issue?

**Comment by muhamad-rizki** [comment]
> @fnando I've checked it with the following version on android
> 
> ```
> "dependencies": {
>     "react": "16.9.0",
>     "react-native": "0.61.5",
>     "rn-qr-generator": "^1.0.1"
>   },
> ```
> 
> And my build.gradle is
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     ext {
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>     }
>     repositories {
>         google()
>         jcenter()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:3.4.2")
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
> 
>         google()
>         jcenter()
>         maven { url 'https://jitpack.io' }
>     }
> }
> ```
> 
> And it works fine.
> 
> Can you please try to remove node modules and install it again?

in my case my build is fail on release version only
